version: '3.9'
services:
  userauthapp:
    build: .
    image: app:django-userauth
    container_name: django_userauth_container
    ports:
       - "8001:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - PORT=8000
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django-userauth
    depends_on:
      - userauthdb

  userauthdb:
    image: postgres
    ports: 
      - "5432"
    environment:
      - POSTGRES_DB=nexaya_user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=grace_123  

volumes:
  postgres_data: