# Generated by Django 4.2.3 on 2023-09-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, max_length=140, null=True)),
                ('transaction_ref', models.CharField(blank=True, max_length=140, null=True)),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=50)),
                ('narration', models.CharField(blank=True, max_length=140, null=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=140, null=True)),
                ('user_email', models.CharField(blank=True, max_length=140, null=True)),
                ('user_token', models.CharField(blank=True, max_length=140, null=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
