# Generated by Django 4.2.3 on 2023-09-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userwallet',
            name='username',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
