# Generated by Django 4.2.3 on 2023-09-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0002_remove_userwallet_user_id_userwallet_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='user_email',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
