# Generated by Django 4.2.3 on 2023-09-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0003_alter_userwallet_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='date_created',
        ),
    ]
